name: car_rent_client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.13.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.4.2
  http: ^1.6.0
  equatable: ^2.0.8
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0
  sliding_segmented_control: ^1.1.0
  material_ui: ^1.1.0
  syncfusion_flutter_sliders: ^34.2.5
  syncfusion_flutter_charts: ^34.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/brands-icons/
    - assets/data/
    - assets/images/app/
    - assets/images/cars/
    - assets/images/cars/abarth-124-spider-1/
    - assets/images/cars/abarth-695-convertible/
    - assets/images/cars/aston-martin-db12-1/
    - assets/images/cars/aston-martin-db9-1/
    - assets/images/cars/aston-martin-dbs-1/
    - assets/images/cars/aston-martin-dbx-1/
    - assets/images/cars/audi-a5-cabrio-1/
    - assets/images/cars/audi-a6-3/
    - assets/images/cars/audi-a7-1/
    - assets/images/cars/audi-a8-1/
    - assets/images/cars/audi-e-tron-gt-1/
    - assets/images/cars/audi-q5-1/
    - assets/images/cars/audi-q6-e-tron-1/
    - assets/images/cars/audi-q7-2/
    - assets/images/cars/audi-q8-2/
    - assets/images/cars/audi-r8-1/
    - assets/images/cars/audi-rs-q3-1/
    - assets/images/cars/audi-rs-q8-1/
    - assets/images/cars/audi-rs3-1/
    - assets/images/cars/audi-rs3-abt-1/
    - assets/images/cars/audi-rs5-1/
    - assets/images/cars/audi-rs6-performance-1/
    - assets/images/cars/audi-rs7-1/
    - assets/images/cars/bentley-bentayga-2/
    - assets/images/cars/bentley-continental-gt-speed-1/
    - assets/images/cars/bentley-flying-spur-1/
    - assets/images/cars/bentley-gtc-2/
    - assets/images/cars/bmw-4-cabrio-4/
    - assets/images/cars/bmw-6/
    - assets/images/cars/bmw-740-xd-2/
    - assets/images/cars/bmw-i7-1/
    - assets/images/cars/bmw-i8-2/
    - assets/images/cars/bmw-i8-cabrio-1/
    - assets/images/cars/bmw-ix-m60-1/
    - assets/images/cars/bmw-m4-convertible/
    - assets/images/cars/bmw-m8-cabrio-1/
    - assets/images/cars/bmw-m8-gran-coupe-1/
    - assets/images/cars/bmw-x4-m-1/
    - assets/images/cars/bmw-x5-2/
    - assets/images/cars/bmw-x6-1/
    - assets/images/cars/bmw-x7-1/
    - assets/images/cars/bmw-xm-1/
    - assets/images/cars/bugatti-chiron-1/
    - assets/images/cars/bugatti-veyron-3/
    - assets/images/cars/carrera-4s-coupe-1/
    - assets/images/cars/carrera-s-cabrio-1/
    - assets/images/cars/carrera-turbo-cabrio-1/
    - assets/images/cars/cupra-formentor-vz5-1/
    - assets/images/cars/ferrari-296-gtb-2/
    - assets/images/cars/ferrari-296-gts-1/
    - assets/images/cars/ferrari-4-8-8-gtb-1/
    - assets/images/cars/ferrari-812-gts-4/
    - assets/images/cars/ferrari-812-superfast-1/
    - assets/images/cars/ferrari-f8-spider-4/
    - assets/images/cars/ferrari-f8-tributo-3/
    - assets/images/cars/ferrari-gt4-lusso-1/
    - assets/images/cars/ferrari-laferrari-1/
    - assets/images/cars/ferrari-portofino-1/
    - assets/images/cars/ferrari-purosangue-1/
    - assets/images/cars/ferrari-roma-1/
    - assets/images/cars/ferrari-roma-spider-1/
    - assets/images/cars/ferrari-sf90-spider-1/
    - assets/images/cars/ferrari-sf90-stradale-1/
    - assets/images/cars/ford-mustang-4/
    - assets/images/cars/gmc-hummer-ev-1/
    - assets/images/cars/infiniti-qx70-1/
    - assets/images/cars/jaguar-f-pace-1/
    - assets/images/cars/jaguar-f-type-cabrio-1/
    - assets/images/cars/jaguar-f-type-cabrio-r/
    - assets/images/cars/jeep-wrangler-hybrid-rubicon-1/
    - assets/images/cars/lamborghini-aventador-2/
    - assets/images/cars/lamborghini-aventador-convertible/
    - assets/images/cars/lamborghini-aventador-svj-coupe-1/
    - assets/images/cars/lamborghini-aventador-svj-roadster-1/
    - assets/images/cars/lamborghini-estoque-1/
    - assets/images/cars/lamborghini-huracan-coupe-1/
    - assets/images/cars/lamborghini-huracan-evo-4/
    - assets/images/cars/lamborghini-huracan-evo-spyder-4/
    - assets/images/cars/lamborghini-huracan-performante/
    - assets/images/cars/lamborghini-huracan-spider/
    - assets/images/cars/lamborghini-huracan-sto-2/
    - assets/images/cars/lamborghini-huracan-tecnica-1/
    - assets/images/cars/lamborghini-revuelto-1/
    - assets/images/cars/lamborghini-roadster-2/
    - assets/images/cars/lamborghini-urus-1/
    - assets/images/cars/lamborghini-urus-s-1/
    - assets/images/cars/land-rover-defender-1/
    - assets/images/cars/land-rover-discovery-sport-1/
    - assets/images/cars/maserati-ghibli-1/
    - assets/images/cars/maserati-grancabrio/
    - assets/images/cars/maserati-grecale-1/
    - assets/images/cars/maserati-levante-2/
    - assets/images/cars/maserati-mc20-1/
    - assets/images/cars/maserati-mc20-cielo-1/
    - assets/images/cars/maserati-quattroporte-1/
    - assets/images/cars/mclaren-650s-2/
    - assets/images/cars/mclaren-720s-spider-1/
    - assets/images/cars/mclaren-750s-1/
    - assets/images/cars/mclaren-765-lt-2/
    - assets/images/cars/mercedes-amg-gt-4-doors-coupe-1/
    - assets/images/cars/mercedes-amg-gt-coupe/
    - assets/images/cars/mercedes-amg-gt-roadster/
    - assets/images/cars/mercedes-c63-cabrio-1/
    - assets/images/cars/mercedes-class-c-cabrio-1/
    - assets/images/cars/mercedes-cle-cabrio-1/
    - assets/images/cars/mercedes-e-cabrio-1/
    - assets/images/cars/mercedes-e-class/
    - assets/images/cars/mercedes-eqs-1/
    - assets/images/cars/mercedes-eqv-1/
    - assets/images/cars/mercedes-g350-1/
    - assets/images/cars/mercedes-g500-4x4/
    - assets/images/cars/mercedes-g63-amg-1/
    - assets/images/cars/mercedes-glc-1/
    - assets/images/cars/mercedes-glc-coupe-1/
    - assets/images/cars/mercedes-gle-amg-1/
    - assets/images/cars/mercedes-gle-coupe-1/
    - assets/images/cars/mercedes-gls-3/
    - assets/images/cars/mercedes-gt-s-2/
    - assets/images/cars/mercedes-maybach-gls-1/
    - assets/images/cars/mercedes-s-class-maybach-1/
    - assets/images/cars/mercedes-s-class-w223-1/
    - assets/images/cars/mercedes-s-w222-armored-2/
    - assets/images/cars/mercedes-s350-long-1/
    - assets/images/cars/mercedes-s500-convertible/
    - assets/images/cars/mercedes-s63-amg-coupe-1/
    - assets/images/cars/mercedes-s63-convertible/
    - assets/images/cars/mercedes-sl63-amg/
    - assets/images/cars/mercedes-sl63-cabrio-1/
    - assets/images/cars/mercedes-sls-1/
    - assets/images/cars/mercedes-v-class-1/
    - assets/images/cars/mercedes-v-class-amg/
    - assets/images/cars/mercedes-v300-amg-4matic-1/
    - assets/images/cars/mercedes-vito-2/
    - assets/images/cars/mini-cooper-cabrio-jcw-1/
    - assets/images/cars/nissan-gt-r-2/
    - assets/images/cars/porsche-718-boxter-1/
    - assets/images/cars/porsche-992-cabrio-2/
    - assets/images/cars/porsche-992-gt3-1/
    - assets/images/cars/porsche-carrera-911s/
    - assets/images/cars/porsche-cayenne-4/
    - assets/images/cars/porsche-macan-s-1/
    - assets/images/cars/porsche-panamera-turbo-s-2/
    - assets/images/cars/porsche-taycan-4/
    - assets/images/cars/range-rover-autobiography/
    - assets/images/cars/range-rover-evoque-2/
    - assets/images/cars/range-rover-evoque-cabrio-4/
    - assets/images/cars/range-rover-sport-2/
    - assets/images/cars/range-rover-sport-svr-2/
    - assets/images/cars/range-rover-velar-2/
    - assets/images/cars/range-rover-vogue-supercharged-1/
    - assets/images/cars/rolls-royce-cullinan-1/
    - assets/images/cars/rolls-royce-dawn-1/
    - assets/images/cars/rolls-royce-drophead/
    - assets/images/cars/rolls-royce-ghost/
    - assets/images/cars/rolls-royce-phantom-1/
    - assets/images/cars/rolls-royce-spectre-1/
    - assets/images/cars/tesla-model-3-performance-1/
    - assets/images/cars/tesla-model-4/
    - assets/images/cars/tesla-model-s-1/
    - assets/images/cars/tesla-model-s-p100dl-1/
    - assets/images/cars/tesla-model-x-90d-1/
    - assets/images/cars/tesla-model-x-plaid-1/
    - assets/images/cars/tesla-model-y-2/
    - assets/images/cars/tesla-model-y-performance-1/
    - assets/images/cars/volvo-xc90-1/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
